[package]
name = "ectoplasm"
version = "0.1.0"
authors = ["Mate Kovacs <mkovaxx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.13.0"
url = "2.2.0"
